### ISSUE TITLE
회원 정보 페이지 구현

### ISSUE THREAD

**Issue by wintersky2** [mbti-organization/main_repository#77]
## 작업 내용

- 작성자의 닉네임을 누르면 해당 작성자의 간단한 정보를 보여주는 페이지로 이동한다.
- 회원 수정 페이지와 회원 정보 페이지를 통일했었지만 따로 만들어 줘야 한다.

## Todo

- [ ] 작성자의 닉네임을 클릭하면 /member/info/{nickname} 페이지로 이동한다. {nickname}은 해당 글 작성자 즉,article.author.nickname으로 값을 보내준다. 

- [ ] GetMapping 메서드에서 nickname 을 PathVariable로 받아준 후 nickname 으로 해당 멤버 객체를 불러온다.

- [ ] model에 멤버 객체를 담아 member_info 템플릿으로 보낸다.

- [ ] member_info 템플릿에서 간단한 회원 정보를 출력하여 준다.
